### ISSUE TITLE
Duplicate studies for Joe Siim

### ISSUE THREAD

**Issue by jmhmd** [ImagingInformatics/hackathon-dataset#28]
Studies ct-0433 and ct-3733 are duplicates. I'll arbitrarily keep ct-3733 and delete the other from the dataset and submit a pull request reflecting that change.

Someone will need to remove the unused duplicate images from the VNA.

**Comment by jmhmd** [comment]
Nevermind, I think Marc already put in a report and key images for ct-0433, so I'll remove ct-3733 instead and keep ct-0433.

**Comment by shadowdoc** [comment]
@mohannadhussain  - can you please remove CT-0433 from the dataset on the dcm4che server, and also update the S3 files when you make the other changes that Jason requested?

**Comment by mohannadhussain** [comment]
Marc - I am not sure if you saw Jason's last comment but he suggested to keep ct-0433 and remove ct-3733. I am not sure if you guys perhaps talked about it online, but I would vote for keeping ct-3733 over ct-3733, because I know Chris Hafey had created KO and PR for ct-0433 (he recruited a radiologist friend to do that for him).

I will hold off making any changes to S3 or VNA until I get a confirmation from either one of you, gentlemen!

**Comment by mohannadhussain** [comment]
I guess I should tag you properly so you'd get notified, @shadowdoc @jmhmd

**Comment by shadowdoc** [comment]
I'm fine with deleting CT-0433.  Interestingly 0433 and 3733 both have the same accession number, so the report will match up just fine with either way.  I've renamed the DiagnosticReport file and removed the 0433 text file and recovered the 3733 text file from git.  @mohannadhussain - go ahead and close when the DICOM changes are made.

**Comment by mohannadhussain** [comment]
@shadowdoc OK, sound good! For the record, there are no changes required to the .txt file from the study that Jason fixed (CT-0858) so you won't see any pull requests from me.

However, I've also just realized that dcm4chee v4 has no easy to delete a study yet, even doing it through the DB isn't much of option because their foreign keys don't cascade on delete..... So, my most convenient choice is going to be emptying the entire DB and re-populating the entire dataset. Before I do so, do you or @jmhmd anticipate more changes to the DICOM files?
